# Find all the available rules by running: swiftlint rules
allow_zero_lintable_files: true

opt_in_rules:
  - anyobject_protocol
  - array_init
  - attributes
  - closure_body_length
  - closure_end_indentation
  - collection_alignment
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - convenience_type
  - duplicate_imports
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - extension_access_modifier
  - fatal_error_message
  - first_where
  - force_unwrapping
  - identical_operands
  - implicit_return
  - indentation_width
  - joined_default_parameter
  - last_where
  - let_var_whitespace
  - literal_expression_end_indentation
  - missing_docs
  - modifier_order
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - number_separator
  - operator_usage_whitespace
  - operator_whitespace
  - override_in_extension
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prohibited_interface_builder
  - prohibited_super_call
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - switch_case_on_newline
  - test_case_accessibility
  - toggle_bool
  - unneeded_break_in_switch
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - unused_import
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - ./**/Pods
  - scripts
  - build
  - derivedData
  - Documenation
  - .git
  - .build
  - Dangerfile.swift
  - Package.swift

# configurable rules can be customized from this configuration file
# binary rules can set their severity level

closure_body_length:
  warning: 30
  error: 40
  
cyclomatic_complexity:
  ignores_case_statements: true

empty_count:
  severity: warning

identifier_name:
  min_length:
    warning: 3
  excluded:
    - id
    - vc

line_length:
  error: 120
  ignores_urls: true

trailing_whitespace:
  ignores_empty_lines: true
