# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

update_fastlane

ENV["FASTLANE_EXPLICIT_OPEN_SIMULATOR"] = "2"

default_platform(:ios)

platform :ios do
  desc "Sanity checks to run on CI"
  lane :sanity_checks do
    swiftlint_strict
    # just unit testing for now, due to a problem with Github Actions
    unit_tests_full_plan
    unit_tests_regional_us
    unit_tests_regional_arg
    # ui_tests
  end

  desc "Build the app"
  lane :build do
    cocoapods
    gym(skip_package_ipa: true)
  end

  desc "Run the unit tests"
  lane :unit_tests do
    run_tests(
      device: "iPhone SE (2nd generation)",
      force_quit_simulator: true,
      reset_simulator: true
    )
  end

  desc "Run the unit tests default plan"
  lane :unit_tests_full_plan do
    run_tests(
      device: "iPhone SE (2nd generation)",
      testplan: "UnitTestsPlan",
      only_test_configurations: "System Config"
    )
  end

  desc "Run the regional unit tests (US Config)"
  lane :unit_tests_regional_us do
    run_tests(
      device: "iPhone SE (2nd generation)",
      testplan: "RegionalTestsPlan",
      only_test_configurations: "United States Config - English"
    )
  end

  desc "Run the regional unit tests (ARG Config)"
  lane :unit_tests_regional_arg do
    run_tests(
      device: "iPhone SE (2nd generation)",
      testplan: "RegionalTestsPlan",
      only_test_configurations: "Argentina Config - Spanish"
    )
  end

  desc "Run the UI tests"
  lane :ui_tests do
    run_tests(
	device: "iPhone SE (2nd generation)",
	testplan:"UITestsPlan"
    )
  end

  desc "Run swiftlint in strict mode"
  lane :swiftlint_strict do
    swiftlint(strict: true)
  end  

end
