name: Upload build to Testflight

on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  upload-build:
    runs-on: macos-latest
    env:
      APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
      APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
      APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }} 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '5'
      - name: Upload to Testflight
        run: fastlane distribute_to_testflight