name: Fastlane

on:
  pull_request

jobs:
  test:
    name: Sanity Checks
    runs-on: macos-11.0

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        pod deintegrate
        pod install --repo-update
      shell: bash
    - name: Bundle Install
      run: bundle install
    - name: Sanity tests
      env:
        SLACK_WEB_HOOK_URL: ${{ secrets.SLACK_WEB_HOOK_URL }}
        SLACK_CI_CHANNEL_NAME: ${{ secrets.CI_CHANNEL_NAME }}
      run: bundle exec fastlane sanity_checks 
